# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Wyrd_config = debug
endif
ifeq ($(config),release)
  Wyrd_config = release
endif
ifeq ($(config),distribution)
  Wyrd_config = distribution
endif

PROJECTS := Wyrd

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Wyrd:
ifneq (,$(Wyrd_config))
	@echo "==== Building Wyrd ($(Wyrd_config)) ===="
	@${MAKE} --no-print-directory -C Wyrd -f Makefile config=$(Wyrd_config)
endif

clean:
	@${MAKE} --no-print-directory -C Wyrd -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  distribution"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Wyrd"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"