name: Build Wyrd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install toolchain
      run: ./buildsystem/build-toolchain.sh
    - name: install dependencies
      run: ./buildsystem/build-dependencies.sh
    - name: build wyrd
      run: ./buildsystem/build-wyrd.sh
   
