name: Build Wyrd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libs
      run: sudo apt install uuid-dev
    - name: pull premake
      run: git clone https://github.com/premake/premake-core.git
    - name: build premake
      run: cd premake-core && make -f Bootstrap.mak linux
