name: Build Wyrd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup linux build environment
      run: ./buildsystem/linux/setup-environment.sh
    - name: Setup and build Wyrd 
      run: ./buildsystem/linux/setup-wyrd.sh
    